In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('myarray',arr)

In [5]:
arr = np.arange(10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [12]:
arr1 = np.load('myarray.npy')

In [13]:
arr2 = arr

In [14]:
np.savez('ziparray.npz',x=arr1,y=arr2)

In [15]:
archived_array = np.load('ziparray.npz')

In [18]:
archived_array['x']

array([0, 1, 2, 3, 4])

In [19]:
archived_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr = np.array([[1,2,3],[4,5,6]])

In [21]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [24]:
arr = np.loadtxt('mytextarray.txt',delimiter=',')

In [25]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [27]:
pwd

u'C:\\Users\\ColinMcLaughlinCrowd\\Documents\\pythoncourse\\Section 3 Learning Numpy'