In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([ 0.03934977,  0.7067423 ,  0.74021094,  0.69519602, -0.04205054,
       -0.5565124 ,  0.66347373,  1.89208921, -0.51943069,  0.7591321 ])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([-1.65713609, -1.8045793 , -2.30983188,  0.17523168,  1.71691193,
       -0.32820913, -2.44645255,  0.67362181,  0.2097332 , -1.39980818])

In [10]:
# binary function
np.add(A,B)

array([-1.61778632, -1.09783699, -1.56962094,  0.8704277 ,  1.67486139,
       -0.88472153, -1.78297882,  2.56571103, -0.30969749, -0.64067609])

In [11]:
np.maximum(A,B)

array([ 0.03934977,  0.7067423 ,  0.74021094,  0.69519602,  1.71691193,
       -0.32820913,  0.66347373,  1.89208921,  0.2097332 ,  0.7591321 ])